### ISSUE TITLE
Methods with multiple parameters 

### ISSUE THREAD

**Issue by karruma** [PierreDuc/ts-method-cache#1]
Hi, 

When method is annotated with @MemoryCache() everything works fine if the method takes only one parameter, but if there's more then it concatenates it and passes the value to the first parameter, so it probably creates a valid cache but the method isn't being evaluated.. 
    
```
 @MemoryCache()
  public method(paramA: string, paramB: string, paramC: number): Observable<number> {
      console.out(paramA);
      console.out(paramB);
      console.out(paramC);
      return Observable.create(observer=>observer.next(paramA + paramC + paramB);
  }
```

  So now when we execute this method what's being logged is:

```
method('stringA', 'stringB', 2).subscribe(result=>console.log(result));

stringAstringB2
undefined
undefined

stringAstringB2undefinedundefined
```
  
  Any chance to fix this?

Regards!

**Comment by PierreDuc** [comment]
@karruma Thank you for your issue. I've resolved the problem.
