### ISSUE TITLE
clearAllCache does not work correctly.

### ISSUE THREAD

**Issue by anchmelev** [PierreDuc/ts-method-cache#2]
Hello, wonderful library!
unfortunately  method `clearAllCache`  service  `MethodCacheService` does not work as expected.
after it is called, an error occurs when calling methods with the decorator `@MemoryCache()`:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
```

**Comment by PierreDuc** [comment]
Hello @Andry361,

Are you using the library inside a nodejs environment? If not, can you provide a minimal reproduction?
